#!/bin/bash

# This file will start the bot with desired configuration
# All necessary infos get echoed over from the main script
# and the command will be executed afterwards. This should
# enable us running as many bots as wanted.

print_msg_newline()
{
	text=$1
	printf '%s\\n' "$text"
}

print_msg()
{
	text=$1
	printf '%s' "$text"
}

move_to_dir()
{
	dir=$1
	cd "$dir"
}

setup_virtualenv()
{
	printf '%s' " - Setting up Python virtualenv..."
	virtualenv -q .
	OUT=$?
	if [ $OUT -eq 0 ] ; then
		print_msg_newline "[DONE]"
	else
		print_msg_newline "[FAIL]"
		print_msg_new ""
		print_msg_new "   Error code $OUT returned !! "
		print_msg_new ""
		print_msg_new " - Exiting..."
		sleep 5
		exit 1
	fi
}

activate_virtualenv()
{
	printf '%s' " - Activating Python virtualenv..."
	source bin/activate
	OUT=$?
	if [ $OUT -eq 0 ] ; then
		print_msg_newline "[DONE]"
	else
		print_msg_newline "[FAIL]"
		print_msg_new ""
		print_msg_new "   Error code $OUT returned !! "
		print_msg_new ""
		print_msg_new " - Exiting..."
		sleep 5
		exit 1
	fi
}
